main:
  push:
    - services:
        - docker
      docker:
        image: node:20
      stages:
        - name: 安装&&构建&&测试
          script:
            - npm ci
            - npm test
            - npm run build

        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .

        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest

        - name: deploy to vm
          image: tencentcom/ssh
          imports: https://cnb.cool/ai-alchemy-factory/project-secrets/-/blob/main/firecrawl-lite-ssh.yml
          settings:
            host: $REMOTE_HOST
            port: $REMOTE_PORT
            username: $REMOTE_USERNAME
            key: $PRIVATE_KEY
            script:
              - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN docker.cnb.cool || exit 1
              - docker pull docker.cnb.cool/ai-alchemy-factory/firecrawl-lite:latest || exit 1
              - docker stop firecrawl-lite || true
              - docker rm firecrawl-lite || true
              - docker run -d -p 80:3000 --name firecrawl-lite --restart=always docker.cnb.cool/ai-alchemy-factory/firecrawl-lite:latest || exit 1
              - sleep 3
              - docker ps | grep -q firecrawl-lite || exit 1
              - docker logs firecrawl-lite || true
              - docker exec firecrawl-lite curl -f http://localhost:3000/health || exit 1