# ============================================================================
# CI/CD Configuration - Keep It Simple, Stupid
# ============================================================================
# Philosophy:
#   1. Don't break production
#   2. Every release is a Git tag
#   3. Keep it simple enough to understand at 3 AM
# ============================================================================

main:
  push:
    - docker:
        image: node:20
        volumes:
          - /root/.npm:cow
          - ./node_modules
      services:
        - docker
      stages:
        - name: test and build
          script: |
            npm ci
            npm test
            npm run build
        
        - name: build dev image
          image: docker:24-cli
          script: |
            DEV_TAG="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev-$(date +%Y%m%d-%H%M%S)"
            echo "${CNB_TOKEN}" | docker login -u "${CNB_TOKEN_USER_NAME}" --password-stdin "${CNB_DOCKER_REGISTRY}"
            docker build -t "${DEV_TAG}" .
            docker push "${DEV_TAG}"

  pull_request:
    - docker:
        image: node:20
        volumes:
          - /root/.npm:cow
          - ./node_modules
      stages:
        - name: install deps
          script: npm ci
        - name: lint check
          script: npm run lint
        - name: unit tests
          script: npm test
        - name: build check
          script: npm run build

# ============================================================================
# Tag Push: Build and Deploy Production
# ============================================================================
"v*.*.*":
  tag_push:
    - docker:
        image: node:20
        volumes:
          - /root/.npm:cow
          - ./node_modules
      services:
        - docker
      stages:
        - name: test and build
          script: |
            npm ci
            npm test
            npm run build
        
        - name: build and push image
          image: docker:24-cli
          script: |
            VERSION="${CNB_BRANCH}"
            IMAGE_TAG="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${VERSION}"
            LATEST_TAG="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
            
            echo "${CNB_TOKEN}" | docker login -u "${CNB_TOKEN_USER_NAME}" --password-stdin "${CNB_DOCKER_REGISTRY}"
            docker build -t "${IMAGE_TAG}" -t "${LATEST_TAG}" .
            docker push "${IMAGE_TAG}"
            docker push "${LATEST_TAG}"
        
        - name: deploy to production
          image: cnbcool/ssh
          imports: https://cnb.cool/ai-alchemy-factory/project-secrets/-/blob/main/firecrawl-lite-ssh.yml
          env:
            DEPLOY_IMAGE: docker.cnb.cool/ai-alchemy-factory/firecrawl-lite:${CNB_BRANCH}
          settings:
            host: ${REMOTE_HOST}
            port: ${REMOTE_PORT}
            username: ${REMOTE_USERNAME}
            key: ${PRIVATE_KEY}
            script:
              - echo "${REGISTRY_TOKEN}" | docker login -u "${REGISTRY_USER}" --password-stdin docker.cnb.cool
              - docker pull ${DEPLOY_IMAGE}
              - docker stop firecrawl-lite || true
              - docker rm firecrawl-lite || true
              - docker run -d -p 80:80 -p 443:443 --name firecrawl-lite --restart=always -v /opt/firecrawl-lite/caddy-data:/data ${DEPLOY_IMAGE}
              - sleep 5
              - docker ps | grep firecrawl-lite

# ============================================================================
# Manual Operations
# ============================================================================
$:
  deploy:
    - stages:
        - name: deploy version
          image: cnbcool/ssh
          imports: https://cnb.cool/ai-alchemy-factory/project-secrets/-/blob/main/firecrawl-lite-ssh.yml
          env:
            DEPLOY_IMAGE: docker.cnb.cool/ai-alchemy-factory/firecrawl-lite:${DEPLOY_VERSION}
          settings:
            host: ${REMOTE_HOST}
            port: ${REMOTE_PORT}
            username: ${REMOTE_USERNAME}
            key: ${PRIVATE_KEY}
            script:
              - echo "${REGISTRY_TOKEN}" | docker login -u "${REGISTRY_USER}" --password-stdin docker.cnb.cool
              - docker pull ${DEPLOY_IMAGE}
              - docker stop firecrawl-lite || true
              - docker rm firecrawl-lite || true
              - docker run -d -p 80:80 -p 443:443 --name firecrawl-lite --restart=always -v /opt/firecrawl-lite/caddy-data:/data ${DEPLOY_IMAGE}
              - docker ps | grep firecrawl-lite
  
  rollback:
    - stages:
        - name: rollback version
          image: cnbcool/ssh
          imports: https://cnb.cool/ai-alchemy-factory/project-secrets/-/blob/main/firecrawl-lite-ssh.yml
          env:
            DEPLOY_IMAGE: docker.cnb.cool/ai-alchemy-factory/firecrawl-lite:${ROLLBACK_VERSION}
          settings:
            host: ${REMOTE_HOST}
            port: ${REMOTE_PORT}
            username: ${REMOTE_USERNAME}
            key: ${PRIVATE_KEY}
            script:
              - echo "${REGISTRY_TOKEN}" | docker login -u "${REGISTRY_USER}" --password-stdin docker.cnb.cool
              - docker pull ${DEPLOY_IMAGE}
              - docker stop firecrawl-lite || true
              - docker rm firecrawl-lite || true
              - docker run -d -p 80:80 -p 443:443 --name firecrawl-lite --restart=always -v /opt/firecrawl-lite/caddy-data:/data ${DEPLOY_IMAGE}
              - docker ps | grep firecrawl-lite
