main:
  push:
    - name: docker-build-and-deploy
      docker:
        image: node:20
      services:
        - docker
      env:
        IMAGE_TAG_BASE: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
      stages:
        - name: docker login
          image: docker:24-cli
          script: |
            set -e
            docker login -u "${CNB_TOKEN_USER_NAME}" -p "${CNB_TOKEN}" "${CNB_DOCKER_REGISTRY}"

        - name: docker build
          image: docker:24-cli
          script: |
            set -e
            TAG_SUFFIX="${CNB_COMMIT_SHA:-${CNB_COMMIT:-latest}}"
            IMAGE_TAG="${IMAGE_TAG_BASE}:${TAG_SUFFIX}"
            docker build -t "${IMAGE_TAG}" .

        - name: docker push
          image: docker:24-cli
          script: |
            set -e
            TAG_SUFFIX="${CNB_COMMIT_SHA:-${CNB_COMMIT:-latest}}"
            IMAGE_TAG="${IMAGE_TAG_BASE}:${TAG_SUFFIX}"
            LATEST_TAG="${IMAGE_TAG_BASE}:latest"
            docker tag "${IMAGE_TAG}" "${LATEST_TAG}"
            docker push "${IMAGE_TAG}"
            docker push "${LATEST_TAG}"
