main:
  push:
    - services:
        - docker
      docker:
        image: node:20
      stages:
        - name: 安装&&构建
          script:
            - npm ci
            - npm run build
        # 同名镜像构建&推送
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest